// reference/archeo-prototype-latest/src/app/components/detail/DetailTopNav.tsx
import { useState } from "react";
import { Button } from "../ui/button";
import { ArrowLeft, Menu, PanelRightClose, PanelRightOpen, Pickaxe } from "lucide-react";
import { useNavigate } from "react-router";
import { useIsMobile } from "../ui/use-mobile";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "../ui/sheet";

interface DetailTopNavProps {
  activityName?: string;
  rightPanelVisible?: boolean;
  onToggleRightPanel?: () => void;
}

export function DetailTopNav({ activityName, rightPanelVisible = true, onToggleRightPanel }: DetailTopNavProps) {
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const [menuOpen, setMenuOpen] = useState(false);

  if (isMobile) {
    return (
      <header className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-3 py-2 bg-white border-b border-[#e5e5e5]">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate("/")}
          className="text-[#1a62ff] hover:text-[#034ae8] hover:bg-blue-50 gap-1 px-2 h-9"
        >
          <ArrowLeft className="size-4" />
          <span className="text-[14px] font-[500]">Späť</span>
        </Button>
        <span className="text-[14px] font-[600] text-[#171717] truncate max-w-[180px] text-center">
          {activityName || "Detail"}
        </span>
        <Button
          variant="outline"
          size="icon"
          className="rounded-lg size-9 border-[#1a62ff] text-[#1a62ff] bg-white hover:bg-blue-50"
          onClick={() => setMenuOpen(true)}
        >
          <Menu className="size-5" />
        </Button>
        <Sheet open={menuOpen} onOpenChange={setMenuOpen}>
          <SheetContent side="right" className="w-[280px]">
            <SheetHeader>
              <SheetTitle>Menu</SheetTitle>
              <SheetDescription className="sr-only">
                Navigation menu
              </SheetDescription>
            </SheetHeader>
            <div className="flex flex-col gap-3 p-4">
              <Button
                variant="outline"
                className="rounded-lg px-3 py-2 h-auto gap-2 border-[#1a62ff] text-[#1a62ff] bg-white hover:bg-blue-50 justify-start"
              >
                <span className="text-[16px] font-[600] tracking-[-0.16px]">
                  Info
                </span>
              </Button>
              <Button
                variant="outline"
                className="rounded-lg px-3 py-2 h-auto gap-2 border-[#1a62ff] text-[#1a62ff] bg-white hover:bg-blue-50 justify-start"
              >
                <span className="text-[16px] font-[600] tracking-[-0.16px]">
                  User
                </span>
              </Button>
            </div>
          </SheetContent>
        </Sheet>
      </header>
    );
  }

  return (
    <header className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-3 py-2 bg-white border-b border-[#e5e5e5]">
      {/* Left: Logo + Späť button */}
      <div className="flex items-center gap-3">
        <Pickaxe className="size-5 text-[#171717]" />
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate("/")}
          className="text-[#1a62ff] hover:text-[#034ae8] hover:bg-blue-50 gap-1 px-2 h-9"
        >
          <ArrowLeft className="size-4" />
          <span className="text-[14px] font-[500]">Späť do Explore</span>
        </Button>
      </div>

      {/* Center: Locality name */}
      <div className="absolute left-1/2 -translate-x-1/2 flex items-center gap-2">
        <span className="text-[16px] font-[700] tracking-[-0.2px] text-[#171717] whitespace-nowrap max-w-[400px] truncate">
          {activityName || "Detail aktivity"}
        </span>
      </div>

      {/* Right: Toggle panel + buttons */}
      <div className="flex items-center gap-2">
        {onToggleRightPanel && (
          <Button
            variant="outline"
            size="sm"
            onClick={onToggleRightPanel}
            className="rounded-lg h-9 px-3 gap-2 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50"
          >
            {rightPanelVisible ? (
              <PanelRightClose className="size-4" />
            ) : (
              <PanelRightOpen className="size-4" />
            )}
            <span className="text-[13px] font-[500]">
              {rightPanelVisible ? "Skryť panel" : "Zobraziť panel"}
            </span>
          </Button>
        )}
        <Button
          variant="outline"
          className="rounded-lg px-3 py-1.5 h-9 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50"
        >
          <span className="text-[14px] font-[600] tracking-[-0.14px]">
            Info
          </span>
        </Button>
        <Button
          variant="outline"
          className="rounded-lg px-3 py-1.5 h-9 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50"
        >
          <span className="text-[14px] font-[600] tracking-[-0.14px]">
            User
          </span>
        </Button>
      </div>
    </header>
  );
}

// src/components/ct/DetailTopNav.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet'
import {
  Search,
  Menu,
  FolderOpen,
  Info,
  User,
  Languages,
  PanelRightClose,
  PanelRightOpen,
} from 'lucide-vue-next'
import { useIsMobile } from '@/composables/useIsMobile'

defineProps<{
  rightPanelOpen: boolean
}>()

const emit = defineEmits<{
  (e: 'toggle-right-panel'): void
}>()

const isMobile = useIsMobile()
const mobileSheetOpen = ref(false)
const searchQuery = ref('')
</script>

<template>
  <nav
    class="fixed top-0 left-0 right-0 z-50 flex items-center border-b border-neutral-200 bg-white px-4 md:px-6"
    :class="isMobile ? 'h-[49px]' : 'h-[57px]'"
    aria-label="Detail navigation"
  >
    <!-- Left: branding + back -->
    <div class="flex min-w-0 flex-shrink-0 items-center gap-3">
      <RouterLink
        to="/"
        class="truncate text-lg font-semibold text-primary-500 hover:text-primary-600"
      >
        Etno Explorer SAV
      </RouterLink>
      <RouterLink
        :to="{ name: 'explore' }"
        class="hidden shrink-0 text-sm text-muted-foreground hover:text-foreground md:inline"
      >
        ← Späť do Explore
      </RouterLink>
    </div>

    <!-- Center: search (desktop only) -->
    <div
      v-if="!isMobile"
      class="flex flex-1 justify-center px-4"
    >
      <div class="relative w-full max-w-md">
        <Search
          class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
          aria-hidden
        />
        <Input
          v-model="searchQuery"
          type="search"
          class="h-9 pl-9"
          placeholder="Search in collection"
          aria-label="Search in collection"
        />
      </div>
    </div>

    <!-- Right: desktop — nav buttons + panel toggle -->
    <div
      v-if="!isMobile"
      class="flex flex-shrink-0 items-center gap-2"
    >
      <Button
        variant="outline"
        size="sm"
        class="gap-1.5"
        aria-label="Collections"
      >
        <FolderOpen class="h-4 w-4" />
        <span class="hidden sm:inline">Collections</span>
      </Button>
      <Button
        variant="outline"
        size="icon"
        class="h-9 w-9"
        aria-label="Info"
      >
        <Info class="h-4 w-4" />
      </Button>
      <Button
        variant="outline"
        size="icon"
        class="h-9 w-9"
        aria-label="User"
      >
        <User class="h-4 w-4" />
      </Button>
      <Button
        variant="outline"
        size="sm"
        aria-label="Language EN/SK"
      >
        EN/SK
      </Button>
      <Button
        variant="outline"
        size="sm"
        class="gap-1.5"
        aria-label="Toggle right panel"
        @click="emit('toggle-right-panel')"
      >
        <PanelRightOpen
          v-if="!rightPanelOpen"
          class="h-4 w-4"
        />
        <PanelRightClose
          v-else
          class="h-4 w-4"
        />
        <span class="hidden sm:inline">
          {{ rightPanelOpen ? 'Skryť panel' : 'Zobraziť panel' }}
        </span>
      </Button>
    </div>

    <!-- Right: mobile — back + menu -->
    <template v-else>
      <RouterLink
        :to="{ name: 'explore' }"
        class="flex-1 text-sm text-primary-600 hover:underline"
      >
        ← Späť do Explore
      </RouterLink>
      <Sheet v-model:open="mobileSheetOpen">
        <SheetTrigger as-child>
          <Button
            variant="outline"
            size="icon"
            class="h-9 w-9"
            aria-label="Open menu"
          >
            <Menu class="h-5 w-5" />
          </Button>
        </SheetTrigger>
        <SheetContent side="right" class="w-[280px] sm:max-w-[320px]">
          <SheetHeader>
            <SheetTitle>Menu</SheetTitle>
          </SheetHeader>
          <div class="mt-6 flex flex-col gap-2">
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <FolderOpen class="h-4 w-4" />
              Collections
            </Button>
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <Info class="h-4 w-4" />
              Info
            </Button>
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <User class="h-4 w-4" />
              User
            </Button>
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <Languages class="h-4 w-4" />
              EN/SK
            </Button>
          </div>
        </SheetContent>
      </Sheet>
    </template>
  </nav>
</template>
