// reference/archeo-prototype-latest/src/app/components/FilterSidebar.tsx
import { useState, useMemo, useEffect, useRef } from "react";
import { ScrollArea } from "./ui/scroll-area";
import {
  ChevronRight,
  ArrowLeft,
  MapPin,
  Building2,
  Search,
  X,
  Check,
  SlidersHorizontal,
} from "lucide-react";
import { Button } from "./ui/button";
import {
  ACTIVITIES,
  FILTER_CATEGORIES,
  getUniqueValues,
  type Activity,
} from "../data/mockData";

interface FilterSidebarProps {
  mobile?: boolean;
  onApply?: () => void;
  activeFilters: Record<string, string[]>;
  onFilterChange: (filters: Record<string, string[]>) => void;
  onSubViewChange?: (isOpen: boolean) => void;
}

type FilterKey = keyof Activity;

// Section label with icon
function SectionLabel({
  label,
  icon,
}: {
  label: string;
  icon: "geo" | "inst";
}) {
  return (
    <div className="flex items-center gap-1 pr-1">
      {icon === "geo" ? (
        <MapPin className="size-4 text-[#737373]" />
      ) : (
        <Building2 className="size-4 text-[#737373]" />
      )}
      <span className="text-[12px] font-[500] text-[#737373]">{label}</span>
    </div>
  );
}

// Filter category row
function FilterItem({
  label,
  selectedCount,
  onClick,
  isActive,
  hasSelection,
}: {
  label: string;
  selectedCount: number;
  onClick: () => void;
  isActive: boolean;
  hasSelection: boolean;
}) {
  return (
    <button
      onClick={onClick}
      className={`w-full h-9 rounded-lg relative flex items-center justify-between px-3 cursor-pointer transition-colors hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1a62ff] ${
        isActive
          ? "border-2 border-[#034ae8] bg-white"
          : hasSelection
          ? "bg-[#e6f0ff] border border-[#b3d1ff]"
          : "bg-white border border-[#e5e5e5]"
      }`}
    >
      <div className="flex items-center gap-2">
        <span
          className={`text-[14px] font-[500] tracking-[-0.14px] ${
            isActive ? "text-[#034ae8]" : "text-[#171717]"
          }`}
        >
          {label}
        </span>
        {selectedCount > 0 && (
          <span className="bg-[#1a62ff] text-white text-[11px] font-[600] min-w-[20px] h-[20px] px-1.5 rounded-full flex items-center justify-center">
            {selectedCount}
          </span>
        )}
      </div>
      <ChevronRight
        className={`size-4 ${isActive ? "text-[#034ae8]" : "text-[#171717]"}`}
      />
    </button>
  );
}

// Sub-view panel (options list with checkboxes)
function FilterSubPanel({
  filterKey,
  label,
  type,
  selected,
  onBack,
  onToggle,
  onReset,
  isMobile,
  hideReset,
  onApply,
  filteredCount,
}: {
  filterKey: FilterKey;
  label: string;
  type: "checkbox" | "radio";
  selected: string[];
  onBack: () => void;
  onToggle: (value: string) => void;
  onReset: () => void;
  isMobile?: boolean;
  hideReset?: boolean;
  onApply?: () => void;
  filteredCount?: number;
}) {
  const [searchQuery, setSearchQuery] = useState("");
  const options = useMemo(() => {
    const values = getUniqueValues(filterKey);
    const counts: Record<string, number> = {};
    for (const a of ACTIVITIES) {
      const val = a[filterKey] as string;
      if (val) counts[val] = (counts[val] || 0) + 1;
    }
    return values.map((v) => ({ value: v, count: counts[v] || 0 }));
  }, [filterKey]);

  const filtered = searchQuery
    ? options.filter((o) =>
        o.value.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : options;

  return (
    <div className={`flex flex-col ${isMobile ? "h-[calc(100dvh-120px)]" : "h-full"}`}>
      {/* Header */}
      <div className="flex items-center justify-between px-1 pb-3">
        <div className="flex items-center gap-2">
          <button
            onClick={onBack}
            className="bg-[#1a62ff] text-white rounded-lg p-2 cursor-pointer hover:bg-[#034ae8] transition-colors"
          >
            <ArrowLeft className="size-5" />
          </button>
          <span className="text-[16px] font-[600] tracking-[-0.16px] text-[#171717]">
            {label}
          </span>
        </div>
        {!hideReset && (
          <button
            onClick={onReset}
            className={`text-[14px] font-[600] tracking-[-0.14px] text-[#ef4444] px-2 py-1 cursor-pointer hover:opacity-80 transition-opacity ${
              selected.length === 0 ? "opacity-50 pointer-events-none" : ""
            }`}
          >
            Reset
          </button>
        )}
      </div>

      {/* Search */}
      <div className="relative mb-2">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-5 text-[#a3a3a3]" />
        <input
          type="text"
          placeholder="Hľadať..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full h-10 rounded-lg border border-[#d4d4d4] pl-10 pr-8 text-[14px] font-[500] text-[#171717] placeholder:text-[#a3a3a3] focus:outline-2 focus:outline-[#1a62ff] focus:border-[#1a62ff]"
        />
        {searchQuery && (
          <button
            onClick={() => setSearchQuery("")}
            className="absolute right-3 top-1/2 -translate-y-1/2 cursor-pointer"
          >
            <X className="size-4 text-[#737373]" />
          </button>
        )}
      </div>

      {/* Options list — scrollable */}
      <ScrollArea className="flex-1 min-h-0">
        <div className="flex flex-col">
          {filtered.map((opt) => {
            const isSelected = selected.includes(opt.value);
            return (
              <button
                key={opt.value}
                onClick={() => onToggle(opt.value)}
                className="flex items-center justify-between py-2.5 px-1 border-b border-[#f3f4f6] cursor-pointer hover:bg-gray-50 transition-colors text-left"
              >
                <div className="flex items-center gap-3">
                  {type === "checkbox" ? (
                    <div
                      className={`size-5 rounded border-2 flex items-center justify-center transition-colors shrink-0 ${
                        isSelected
                          ? "bg-[#1a62ff] border-[#1a62ff]"
                          : "border-[#d4d4d4] bg-white"
                      }`}
                    >
                      {isSelected && (
                        <Check className="size-3.5 text-white" />
                      )}
                    </div>
                  ) : (
                    <div
                      className={`size-5 rounded-full border-2 flex items-center justify-center transition-colors shrink-0 ${
                        isSelected ? "border-[#1a62ff]" : "border-[#d4d4d4]"
                      }`}
                    >
                      {isSelected && (
                        <div className="size-2.5 rounded-full bg-[#1a62ff]" />
                      )}
                    </div>
                  )}
                  <span className="text-[14px] font-[500] text-[#171717]">
                    {opt.value}
                  </span>
                </div>
                <span className="text-[14px] font-[500] text-[#1a62ff] shrink-0 ml-2">
                  {opt.count}
                </span>
              </button>
            );
          })}
        </div>
      </ScrollArea>

      {/* Mobile: CTA at bottom of sub-panel */}
      {isMobile && onApply && (
        <div className="pt-3 shrink-0">
          <Button
            onClick={onApply}
            className="w-full bg-[#1a62ff] hover:bg-[#034ae8] text-white rounded-lg h-10 gap-2"
          >
            <span>Zobraziť {filteredCount ?? 0} výsledkov</span>
            <MapPin className="size-4" />
          </Button>
        </div>
      )}
    </div>
  );
}

// ===== DESKTOP: Two-panel filter =====
function DesktopFilterContent({
  activeFilters,
  onFilterChange,
  onSubViewChange,
}: FilterSidebarProps) {
  const [subView, setSubView] = useState<{
    key: FilterKey;
    label: string;
    type: "checkbox" | "radio";
  } | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const handleSetSubView = (
    view: { key: FilterKey; label: string; type: "checkbox" | "radio" } | null
  ) => {
    setSubView(view);
    onSubViewChange?.(view !== null);
  };

  // Close sub-view on outside click (desktop)
  useEffect(() => {
    if (!subView) return;
    function handleOutsideClick(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        handleSetSubView(null);
      }
    }
    document.addEventListener("mousedown", handleOutsideClick);
    return () => document.removeEventListener("mousedown", handleOutsideClick);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [subView]);

  const handleToggle = (filterKey: string, value: string) => {
    const currentCat = [
      ...FILTER_CATEGORIES.geographic,
      ...FILTER_CATEGORIES.institutional,
    ].find((c) => c.key === filterKey);
    const isRadio = currentCat?.type === "radio";

    const current = activeFilters[filterKey] || [];
    let next: string[];

    if (isRadio) {
      next = current.includes(value) ? [] : [value];
    } else {
      next = current.includes(value)
        ? current.filter((v) => v !== value)
        : [...current, value];
    }

    onFilterChange({ ...activeFilters, [filterKey]: next });
  };

  const handleResetFilter = (filterKey: string) => {
    const updated = { ...activeFilters };
    delete updated[filterKey];
    onFilterChange(updated);
  };

  const handleResetAll = () => {
    onFilterChange({});
  };

  const totalActive = Object.values(activeFilters).reduce(
    (sum, arr) => sum + arr.length,
    0
  );

  return (
    <div className="flex items-start gap-3" ref={containerRef}>
      {/* Panel 1: Category list — wider 280px */}
      <div className="w-[280px] bg-white rounded-xl shadow-lg border border-[#e5e5e5] flex flex-col max-h-[calc(100vh-90px)] overflow-hidden">
        <div className="p-4 pb-0">
          {/* Header */}
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-1.5">
              <SlidersHorizontal className="size-5 text-[#171717]" />
              <span className="text-[18px] font-[700] tracking-[-0.36px] text-[#171717]">
                Filter Aktivít
              </span>
            </div>
            <button
              onClick={handleResetAll}
              className={`text-[14px] font-[600] tracking-[-0.14px] text-[#ef4444] px-1 py-0.5 cursor-pointer hover:opacity-80 transition-opacity ${
                totalActive === 0 ? "opacity-50 pointer-events-none" : ""
              }`}
            >
              Reset all
            </button>
          </div>
        </div>

        <ScrollArea className="flex-1 px-4 pb-4">
          <div className="flex flex-col gap-4">
            {/* Geographic filters */}
            <div className="flex flex-col gap-2">
              <SectionLabel label="Geografické filtre" icon="geo" />
              <div className="flex flex-col gap-2">
                {FILTER_CATEGORIES.geographic.map((cat) => (
                  <FilterItem
                    key={cat.key}
                    label={cat.label}
                    selectedCount={(activeFilters[cat.key] || []).length}
                    hasSelection={(activeFilters[cat.key] || []).length > 0}
                    isActive={subView?.key === cat.key}
                    onClick={() =>
                      handleSetSubView(
                        subView?.key === cat.key
                          ? null
                          : {
                              key: cat.key as FilterKey,
                              label: cat.label,
                              type: cat.type,
                            }
                      )
                    }
                  />
                ))}
              </div>
            </div>

            {/* Institutional filters */}
            <div className="flex flex-col gap-2">
              <SectionLabel label="Inštitucionálne filtre" icon="inst" />
              <div className="flex flex-col gap-2">
                {FILTER_CATEGORIES.institutional.map((cat) => (
                  <FilterItem
                    key={cat.key}
                    label={cat.label}
                    selectedCount={(activeFilters[cat.key] || []).length}
                    hasSelection={(activeFilters[cat.key] || []).length > 0}
                    isActive={subView?.key === cat.key}
                    onClick={() =>
                      handleSetSubView(
                        subView?.key === cat.key
                          ? null
                          : {
                              key: cat.key as FilterKey,
                              label: cat.label,
                              type: cat.type,
                            }
                      )
                    }
                  />
                ))}
              </div>
            </div>
          </div>
        </ScrollArea>
      </div>

      {/* Panel 2: Sub-view (options list) — scrollable within max-height */}
      {subView && (
        <div className="w-[320px] bg-white rounded-xl shadow-lg border border-[#e5e5e5] max-h-[calc(100vh-90px)] overflow-hidden flex flex-col">
          <div className="p-4 flex-1 min-h-0 flex flex-col">
            <FilterSubPanel
              filterKey={subView.key}
              label={subView.label}
              type={subView.type}
              selected={activeFilters[subView.key] || []}
              onBack={() => handleSetSubView(null)}
              onToggle={(value) => handleToggle(subView.key, value)}
              onReset={() => handleResetFilter(subView.key)}
            />
          </div>
        </div>
      )}
    </div>
  );
}

// ===== MOBILE: Step-by-step filter =====
function MobileFilterContent({
  activeFilters,
  onFilterChange,
  onApply,
}: FilterSidebarProps) {
  const [subView, setSubView] = useState<{
    key: FilterKey;
    label: string;
    type: "checkbox" | "radio";
  } | null>(null);

  const handleToggle = (filterKey: string, value: string) => {
    const currentCat = [
      ...FILTER_CATEGORIES.geographic,
      ...FILTER_CATEGORIES.institutional,
    ].find((c) => c.key === filterKey);
    const isRadio = currentCat?.type === "radio";

    const current = activeFilters[filterKey] || [];
    let next: string[];

    if (isRadio) {
      next = current.includes(value) ? [] : [value];
    } else {
      next = current.includes(value)
        ? current.filter((v) => v !== value)
        : [...current, value];
    }

    onFilterChange({ ...activeFilters, [filterKey]: next });
  };

  const handleResetFilter = (filterKey: string) => {
    const updated = { ...activeFilters };
    delete updated[filterKey];
    onFilterChange(updated);
  };

  const handleResetAll = () => {
    onFilterChange({});
  };

  const totalActive = Object.values(activeFilters).reduce(
    (sum, arr) => sum + arr.length,
    0
  );

  const filteredCount = useMemo(() => {
    let filtered = ACTIVITIES;
    for (const [key, values] of Object.entries(activeFilters)) {
      if (values.length > 0) {
        filtered = filtered.filter((a) =>
          values.includes(a[key as keyof Activity] as string)
        );
      }
    }
    return filtered.length;
  }, [activeFilters]);

  // Sub-view (replaces main view on mobile)
  if (subView) {
    return (
      <FilterSubPanel
        filterKey={subView.key}
        label={subView.label}
        type={subView.type}
        selected={activeFilters[subView.key] || []}
        onBack={() => setSubView(null)}
        onToggle={(value) => handleToggle(subView.key, value)}
        onReset={() => handleResetFilter(subView.key)}
        isMobile
        hideReset
        onApply={onApply}
        filteredCount={filteredCount}
      />
    );
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Geographic filters */}
      <div className="flex flex-col gap-2">
        <SectionLabel label="Geografické filtre" icon="geo" />
        <div className="flex flex-col gap-2">
          {FILTER_CATEGORIES.geographic.map((cat) => (
            <FilterItem
              key={cat.key}
              label={cat.label}
              selectedCount={(activeFilters[cat.key] || []).length}
              hasSelection={(activeFilters[cat.key] || []).length > 0}
              isActive={false}
              onClick={() =>
                setSubView({
                  key: cat.key as FilterKey,
                  label: cat.label,
                  type: cat.type,
                })
              }
            />
          ))}
        </div>
      </div>

      {/* Institutional filters */}
      <div className="flex flex-col gap-2">
        <SectionLabel label="Inštitucionálne filtre" icon="inst" />
        <div className="flex flex-col gap-2">
          {FILTER_CATEGORIES.institutional.map((cat) => (
            <FilterItem
              key={cat.key}
              label={cat.label}
              selectedCount={(activeFilters[cat.key] || []).length}
              hasSelection={(activeFilters[cat.key] || []).length > 0}
              isActive={false}
              onClick={() =>
                setSubView({
                  key: cat.key as FilterKey,
                  label: cat.label,
                  type: cat.type,
                })
              }
            />
          ))}
        </div>
      </div>

      {/* Apply button */}
      <Button
        onClick={onApply}
        className="w-full bg-[#1a62ff] hover:bg-[#034ae8] text-white rounded-lg mt-4 h-10 gap-2"
      >
        <span>Zobraziť {filteredCount} výsledkov</span>
        <MapPin className="size-4" />
      </Button>

      {/* Reset all — below CTA */}
      {totalActive > 0 && (
        <button
          onClick={handleResetAll}
          className="w-full text-center text-[14px] font-[600] text-[#ef4444] py-2 mt-1 cursor-pointer hover:opacity-80 transition-opacity"
        >
          Resetovať všetky filtre ({totalActive})
        </button>
      )}
    </div>
  );
}

// ===== Main export =====
export function FilterSidebar(props: FilterSidebarProps) {
  if (props.mobile) {
    return <MobileFilterContent {...props} />;
  }

  return <DesktopFilterContent {...props} />;
}

// src/components/ct/FilterSidebar.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { FILTER_CATEGORIES, getOptionsWithCounts } from '@/data/mockData'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Tag, MapPin, FileText, ChevronRight, ArrowLeft, X, Search, SlidersHorizontal, Check } from 'lucide-vue-next'

const props = withDefaults(
  defineProps<{
    activeFilters: Record<string, string[]>
    mobile?: boolean
    filteredCount?: number
    /** Desktop: which category sub-panel is open (filter key). Lifted from parent for two-panel layout. */
    openSubPanelKey?: string | null
  }>(),
  { mobile: false, filteredCount: 0, openSubPanelKey: null }
)

const emit = defineEmits<{
  (e: 'update:activeFilters', payload: Record<string, string[]>): void
  (e: 'apply'): void
  (e: 'update:openSubPanelKey', key: string | null): void
}>()

// Mobile only: which category sub-panel is open (filter key)
const selectedCategoryKey = ref<string | null>(null)

// Desktop: which category sub-panel is open (internal state so click always works)
const desktopSubPanelKey = ref<string | null>(null)
// Sync from parent when e.g. click-outside closes the panel
watch(
  () => props.openSubPanelKey,
  (v) => { desktopSubPanelKey.value = v ?? null },
  { immediate: true }
)

// Search query per expanded category (desktop) or for mobile sub-panel
const searchQuery = ref<Record<string, string>>({})

const categoryOrder = ['thematic', 'geographic', 'formal'] as const

const iconMap = {
  Tag,
  MapPin,
  FileText,
}

function getSectionIcon(iconName: keyof typeof iconMap) {
  return iconMap[iconName] ?? FileText
}

function getSelectedCount(key: string): number {
  return props.activeFilters[key]?.length ?? 0
}

function isSelected(key: string, value: string): boolean {
  return props.activeFilters[key]?.includes(value) ?? false
}

function setValue(filterKey: string, value: string, selected: boolean) {
  const current = props.activeFilters[filterKey] ?? []
  const next = selected
    ? (current.includes(value) ? current : [...current, value])
    : current.filter((v) => v !== value)
  const nextFilters = { ...props.activeFilters }
  if (next.length) nextFilters[filterKey] = next
  else delete nextFilters[filterKey]
  emit('update:activeFilters', nextFilters)
}

function clearCategory(filterKey: string) {
  const next = { ...props.activeFilters }
  delete next[filterKey]
  emit('update:activeFilters', next)
}

function clearAll() {
  emit('update:activeFilters', {})
  if (props.mobile) selectedCategoryKey.value = null
}

function getSearchKey(filterKey: string): string {
  return searchQuery.value[filterKey] ?? ''
}

function setSearchKey(filterKey: string, q: string) {
  searchQuery.value = { ...searchQuery.value, [filterKey]: q }
}

function getFilteredOptions(filterKey: string): { value: string; count: number }[] {
  const options = getOptionsWithCounts(filterKey)
  const q = (getSearchKey(filterKey) ?? '').trim().toLowerCase()
  if (!q) return options
  return options.filter((o) => o.value.toLowerCase().includes(q))
}

function openMobileCategory(key: string) {
  selectedCategoryKey.value = key
}

function closeMobileSubPanel() {
  selectedCategoryKey.value = null
}

/** Desktop: open second panel for this category */
function openDesktopSubPanel(key: string) {
  desktopSubPanelKey.value = key
  emit('update:openSubPanelKey', key)
}

/** Desktop: close second panel */
function closeDesktopSubPanel() {
  desktopSubPanelKey.value = null
  emit('update:openSubPanelKey', null)
}

function getCategoryLabel(filterKey: string): string {
  for (const cat of Object.values(FILTER_CATEGORIES)) {
    const f = cat.filters.find((x) => x.key === filterKey)
    if (f) return f.label
  }
  return filterKey
}

const totalActiveCount = computed(() =>
  Object.values(props.activeFilters).reduce((sum, arr) => sum + (arr?.length ?? 0), 0)
)
</script>

<template>
  <div
    class="flex h-full flex-col bg-white"
    :class="mobile ? 'w-full' : 'min-w-0 flex-1'"
  >
    <!-- Desktop: two-panel layout (Archeo-style rounded-xl shadow-lg) -->
    <template v-if="!mobile">
      <div class="flex h-full max-h-[calc(100vh-90px)] min-w-0 overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-lg">
        <!-- Panel 1: category list 280px -->
        <div class="flex w-[280px] shrink-0 flex-col overflow-hidden">
          <div class="flex items-center justify-between p-4 pb-0 mb-3">
            <div class="flex items-center gap-1.5">
              <SlidersHorizontal class="h-5 w-5 text-foreground" aria-hidden />
              <span class="text-lg font-bold tracking-tight text-foreground">Filter Aktivít</span>
            </div>
            <button
              type="button"
              class="text-sm font-semibold text-destructive px-1 py-0.5 transition-opacity hover:opacity-80"
              :class="totalActiveCount === 0 && 'opacity-50 pointer-events-none'"
              @click="clearAll"
            >
              Reset all
            </button>
          </div>
          <ScrollArea class="flex-1 px-4 pb-4">
            <div class="flex flex-col gap-4">
              <template v-for="catKey in categoryOrder" :key="catKey">
                <template v-if="FILTER_CATEGORIES[catKey]">
                  <div class="flex flex-col gap-2">
                    <div class="flex items-center gap-1 pr-1">
                      <component :is="getSectionIcon(FILTER_CATEGORIES[catKey].icon)" class="h-4 w-4 text-muted-foreground" />
                      <span class="text-[12px] font-medium text-muted-foreground">{{ FILTER_CATEGORIES[catKey].label }}</span>
                    </div>
                    <div class="flex flex-col gap-2">
                      <button
                        v-for="filter in FILTER_CATEGORIES[catKey].filters"
                        :key="filter.key"
                        type="button"
                        class="flex h-9 w-full cursor-pointer items-center justify-between rounded-lg border px-3 transition-colors hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-500"
                        :class="[
                          desktopSubPanelKey === filter.key
                            ? 'border-2 border-primary-600 bg-white'
                            : getSelectedCount(filter.key) > 0
                              ? 'border border-primary-200 bg-primary-50'
                              : 'border border-neutral-200 bg-white',
                        ]"
                        @click.stop="openDesktopSubPanel(filter.key)"
                      >
                        <div class="flex items-center gap-2 min-w-0">
                          <span
                            class="truncate text-sm font-medium tracking-tight"
                            :class="desktopSubPanelKey === filter.key ? 'text-primary-600' : 'text-foreground'"
                          >
                            {{ filter.label }}
                          </span>
                          <span
                            v-if="getSelectedCount(filter.key) > 0"
                            class="flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full bg-primary-500 px-1.5 text-[11px] font-semibold text-white"
                          >
                            {{ getSelectedCount(filter.key) }}
                          </span>
                        </div>
                        <ChevronRight
                          class="h-4 w-4 shrink-0"
                          :class="desktopSubPanelKey === filter.key ? 'text-primary-600' : 'text-foreground'"
                        />
                      </button>
                    </div>
                  </div>
                </template>
              </template>
            </div>
          </ScrollArea>
        </div>
        <!-- Panel 2: sub-panel 320px (Archeo: blue back, red Reset, search + option list) -->
        <div
          v-if="desktopSubPanelKey"
          class="flex w-[320px] shrink-0 flex-col border-l border-neutral-200 bg-white"
        >
          <div class="flex items-center justify-between gap-2 px-1 pb-3 pt-4">
            <div class="flex items-center gap-2">
              <Button
                type="button"
                size="icon"
                class="h-9 w-9 shrink-0 rounded-lg bg-primary-500 text-white hover:bg-primary-600"
                aria-label="Späť"
                @click="closeDesktopSubPanel"
              >
                <ArrowLeft class="h-5 w-5" />
              </Button>
              <span class="text-base font-semibold tracking-tight text-foreground">{{ getCategoryLabel(desktopSubPanelKey) }}</span>
            </div>
            <button
              type="button"
              class="text-sm font-semibold text-destructive px-2 py-1 transition-opacity hover:opacity-80"
              :class="(activeFilters[desktopSubPanelKey]?.length ?? 0) === 0 && 'opacity-50 pointer-events-none'"
              @click="clearCategory(desktopSubPanelKey)"
            >
              Reset
            </button>
          </div>
          <div class="flex flex-1 flex-col overflow-hidden px-4 pb-4">
            <div class="relative mb-2">
              <Search class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" aria-hidden />
              <Input
                :model-value="getSearchKey(desktopSubPanelKey)"
                type="search"
                class="h-10 pl-10 pr-8 rounded-lg border-neutral-300 focus:border-primary-500 focus-visible:ring-2 focus-visible:ring-primary-500"
                placeholder="Hľadať..."
                @update:model-value="setSearchKey(desktopSubPanelKey, $event)"
              />
              <button
                v-if="getSearchKey(desktopSubPanelKey)"
                type="button"
                class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                aria-label="Vymazať"
                @click="setSearchKey(desktopSubPanelKey, '')"
              >
                <X class="h-4 w-4" />
              </button>
            </div>
            <ScrollArea class="flex-1 min-h-0">
              <div class="flex flex-col">
                <button
                  v-for="opt in getFilteredOptions(desktopSubPanelKey)"
                  :key="opt.value"
                  type="button"
                  class="flex cursor-pointer items-center justify-between border-b border-neutral-100 py-2.5 px-1 text-left transition-colors hover:bg-neutral-50"
                  @click="setValue(desktopSubPanelKey, opt.value, !isSelected(desktopSubPanelKey, opt.value))"
                >
                  <div class="flex items-center gap-3">
                    <div
                      class="flex h-5 w-5 shrink-0 items-center justify-center rounded border-2 transition-colors"
                      :class="isSelected(desktopSubPanelKey, opt.value) ? 'border-primary-500 bg-primary-500' : 'border-neutral-300 bg-white'"
                    >
                      <Check
                        v-if="isSelected(desktopSubPanelKey, opt.value)"
                        class="h-3.5 w-3.5 text-white"
                      />
                    </div>
                    <span class="text-sm font-medium text-foreground">{{ opt.value }}</span>
                  </div>
                  <span class="ml-2 shrink-0 text-sm font-medium text-primary-500">{{ opt.count }}</span>
                </button>
              </div>
            </ScrollArea>
          </div>
        </div>
      </div>
    </template>

    <!-- Mobile: single-panel layout (Archeo-style step flow + CTA with MapPin) -->
    <template v-else>
      <!-- Mobile step 2: sub-panel -->
      <template v-if="selectedCategoryKey">
        <div class="flex flex-1 flex-col overflow-hidden">
          <div class="flex items-center justify-between gap-2 px-1 pb-3 pt-4">
            <div class="flex items-center gap-2">
              <Button
                type="button"
                size="icon"
                class="h-9 w-9 shrink-0 rounded-lg bg-primary-500 text-white hover:bg-primary-600"
                aria-label="Späť"
                @click="closeMobileSubPanel"
              >
                <ArrowLeft class="h-5 w-5" />
              </Button>
              <span class="text-base font-semibold tracking-tight text-foreground">{{ getCategoryLabel(selectedCategoryKey) }}</span>
            </div>
          </div>
          <div class="flex flex-1 flex-col overflow-hidden px-4 pb-4">
            <div class="relative mb-2">
              <Search class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" aria-hidden />
              <Input
                :model-value="getSearchKey(selectedCategoryKey)"
                type="search"
                class="h-10 pl-10 pr-8 rounded-lg"
                placeholder="Hľadať..."
                @update:model-value="setSearchKey(selectedCategoryKey, $event)"
              />
              <button
                v-if="getSearchKey(selectedCategoryKey)"
                type="button"
                class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                aria-label="Vymazať"
                @click="setSearchKey(selectedCategoryKey, '')"
              >
                <X class="h-4 w-4" />
              </button>
            </div>
            <ScrollArea class="flex-1 min-h-0">
              <div class="flex flex-col">
                <button
                  v-for="opt in getFilteredOptions(selectedCategoryKey)"
                  :key="opt.value"
                  type="button"
                  class="flex cursor-pointer items-center justify-between border-b border-neutral-100 py-2.5 px-1 text-left transition-colors hover:bg-neutral-50"
                  @click="setValue(selectedCategoryKey, opt.value, !isSelected(selectedCategoryKey, opt.value))"
                >
                  <div class="flex items-center gap-3">
                    <div
                      class="flex h-5 w-5 shrink-0 items-center justify-center rounded border-2 transition-colors"
                      :class="isSelected(selectedCategoryKey, opt.value) ? 'border-primary-500 bg-primary-500' : 'border-neutral-300 bg-white'"
                    >
                      <Check
                        v-if="isSelected(selectedCategoryKey, opt.value)"
                        class="h-3.5 w-3.5 text-white"
                      />
                    </div>
                    <span class="text-sm font-medium text-foreground">{{ opt.value }}</span>
                  </div>
                  <span class="ml-2 shrink-0 text-sm font-medium text-primary-500">{{ opt.count }}</span>
                </button>
              </div>
            </ScrollArea>
          </div>
          <div class="flex flex-col gap-2 border-t border-neutral-200 p-3">
            <Button class="w-full gap-2" @click="emit('apply')">
              <span>Zobraziť {{ filteredCount }} výsledkov</span>
              <MapPin class="h-4 w-4" />
            </Button>
          </div>
        </div>
      </template>

      <!-- Mobile step 1: category list -->
      <template v-else>
        <div class="flex items-center justify-between border-b border-neutral-200 p-4 pb-0 mb-3">
          <span class="text-lg font-bold tracking-tight text-foreground">Filter Aktivít</span>
          <button
            type="button"
            class="text-sm font-semibold text-destructive transition-opacity hover:opacity-80"
            :class="totalActiveCount === 0 && 'opacity-50 pointer-events-none'"
            @click="clearAll"
          >
            Reset all
          </button>
        </div>
        <ScrollArea class="flex-1">
          <div class="flex flex-col gap-4 px-4 pb-4">
            <template v-for="catKey in categoryOrder" :key="catKey">
              <template v-if="FILTER_CATEGORIES[catKey]">
                <div class="flex flex-col gap-2">
                  <div class="flex items-center gap-1 pr-1">
                    <component :is="getSectionIcon(FILTER_CATEGORIES[catKey].icon)" class="h-4 w-4 text-muted-foreground" />
                    <span class="text-[12px] font-medium text-muted-foreground">{{ FILTER_CATEGORIES[catKey].label }}</span>
                  </div>
                  <div class="flex flex-col gap-2">
                    <button
                      v-for="filter in FILTER_CATEGORIES[catKey].filters"
                      :key="filter.key"
                      type="button"
                      class="flex h-9 w-full cursor-pointer items-center justify-between rounded-lg border border-neutral-200 bg-white px-3 transition-colors hover:bg-neutral-50"
                      :class="getSelectedCount(filter.key) > 0 && 'border-primary-200 bg-primary-50'"
                      @click="openMobileCategory(filter.key)"
                    >
                      <div class="flex items-center gap-2 min-w-0">
                        <span class="truncate text-sm font-medium text-foreground">{{ filter.label }}</span>
                        <span
                          v-if="getSelectedCount(filter.key) > 0"
                          class="flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full bg-primary-500 px-1.5 text-[11px] font-semibold text-white"
                        >
                          {{ getSelectedCount(filter.key) }}
                        </span>
                      </div>
                      <ChevronRight class="h-4 w-4 shrink-0 text-foreground" />
                    </button>
                  </div>
                </div>
              </template>
            </template>
          </div>
        </ScrollArea>
        <div class="flex flex-col gap-2 border-t border-neutral-200 p-3">
          <Button class="w-full gap-2" @click="emit('apply')">
            <span>Zobraziť {{ filteredCount }} výsledkov</span>
            <MapPin class="h-4 w-4" />
          </Button>
          <button
            v-if="totalActiveCount > 0"
            type="button"
            class="w-full py-2 text-center text-sm font-semibold text-destructive transition-opacity hover:opacity-80"
            @click="clearAll"
          >
            Resetovať všetky filtre ({{ totalActiveCount }})
          </button>
        </div>
      </template>
    </template>
  </div>
</template>
