// reference/archeo-prototype-latest/src/app/components/TopNav.tsx
import { useState } from "react";
import { Button } from "./ui/button";
import { Info, User, Menu, Pickaxe, SlidersHorizontal } from "lucide-react";
import { useIsMobile } from "./ui/use-mobile";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "./ui/sheet";

interface TopNavProps {
  onFilterToggle?: () => void;
  filterOpen?: boolean;
  activeFilterCount?: number;
}

export function TopNav({
  onFilterToggle,
  filterOpen,
  activeFilterCount = 0,
}: TopNavProps) {
  const isMobile = useIsMobile();
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-white border-b border-[#e5e5e5]">
      <div className="flex items-center justify-between px-3 py-2">
        {/* Left side: Filter button */}
        <div className="flex items-center gap-2">
          <Button
            onClick={onFilterToggle}
            variant="outline"
            className={`rounded-lg px-3 py-2 h-auto gap-2 ${
              filterOpen
                ? "bg-[#1a62ff] hover:bg-[#034ae8] text-white border-[#1a62ff]"
                : "border-[#e5e5e5] text-[#374151] hover:bg-gray-50"
            }`}
          >
            <SlidersHorizontal className="size-4" />
            <span className="text-[14px] font-[600] tracking-[-0.14px]">
              {isMobile ? "Filter" : "Filter"}
            </span>
            {activeFilterCount > 0 && (
              <span className={`text-[11px] font-[600] min-w-[20px] h-[20px] px-1.5 rounded-full flex items-center justify-center ${
                filterOpen
                  ? "bg-white text-[#1a62ff]"
                  : "bg-[#1a62ff] text-white"
              }`}>
                {activeFilterCount}
              </span>
            )}
          </Button>
        </div>

        {/* Center: Archeo Explorer branding */}
        <div className="flex items-center gap-2 absolute left-1/2 -translate-x-1/2">
          <Pickaxe className="size-5 text-[#171717]" />
          <span className="text-[16px] font-[700] tracking-[-0.36px] text-[#171717] whitespace-nowrap">
            {isMobile ? "Archeo SAV" : "Archeo Explorer"}
          </span>
        </div>

        {/* Right side */}
        <div className="flex items-center gap-2">
          {isMobile ? (
            <>
              <Button
                variant="outline"
                size="icon"
                className="rounded-lg size-10 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50"
                onClick={() => setMenuOpen(true)}
              >
                <Menu className="size-5" />
              </Button>
              <Sheet open={menuOpen} onOpenChange={setMenuOpen}>
                <SheetContent side="right" className="w-[280px]">
                  <SheetHeader>
                    <SheetTitle>Menu</SheetTitle>
                    <SheetDescription className="sr-only">
                      Navigation menu
                    </SheetDescription>
                  </SheetHeader>
                  <div className="flex flex-col gap-3 p-4">
                    <Button
                      variant="outline"
                      className="rounded-lg px-3 py-2 h-auto gap-2 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50 justify-start"
                    >
                      <Info className="size-5" />
                      <span className="text-[16px] font-[600] tracking-[-0.16px]">
                        Info
                      </span>
                    </Button>
                    <Button
                      variant="outline"
                      className="rounded-lg px-3 py-2 h-auto gap-2 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50 justify-start"
                    >
                      <User className="size-5" />
                      <span className="text-[16px] font-[600] tracking-[-0.16px]">
                        User
                      </span>
                    </Button>
                  </div>
                </SheetContent>
              </Sheet>
            </>
          ) : (
            <>
              <Button
                variant="outline"
                className="rounded-lg px-3 py-2 h-auto gap-2 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50"
              >
                <Info className="size-5" />
                <span className="text-[14px] font-[600] tracking-[-0.14px]">
                  Info
                </span>
              </Button>
              <Button
                variant="outline"
                className="rounded-lg px-3 py-2 h-auto gap-2 border-[#e5e5e5] text-[#374151] bg-white hover:bg-gray-50"
              >
                <User className="size-5" />
                <span className="text-[14px] font-[600] tracking-[-0.14px]">
                  User
                </span>
              </Button>
            </>
          )}
        </div>
      </div>
    </header>
  );
}

// src/components/ct/TopNav.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet'
import {
  SlidersHorizontal,
  Search,
  Menu,
  FolderOpen,
  Info,
  User,
  Languages,
  X,
} from 'lucide-vue-next'
import { useIsMobile } from '@/composables/useIsMobile'

const props = defineProps<{
  filterOpen: boolean
  activeFilterCount: number
  searchQuery?: string
}>()

const emit = defineEmits<{
  (e: 'toggle-filter'): void
  (e: 'update:searchQuery', value: string): void
}>()

const isMobile = useIsMobile()
const mobileSheetOpen = ref(false)
</script>

<template>
  <!-- Desktop nav: single row -->
  <nav
    v-if="!isMobile"
    class="fixed top-0 left-0 right-0 z-50 flex h-[57px] items-center border-b border-neutral-200 bg-white px-4 md:px-6 focus-within:outline-none"
    aria-label="Main navigation"
  >
    <div class="flex min-w-0 flex-shrink-0 items-center gap-2">
      <span class="truncate text-lg font-semibold text-primary-500">
        Etno Explorer SAV
      </span>
      <div class="relative">
        <Button
          type="button"
          size="icon"
          class="h-9 w-9 bg-primary-500 text-white hover:bg-primary-600"
          aria-label="Toggle filters"
          @click="emit('toggle-filter')"
        >
          <SlidersHorizontal class="h-4 w-4" />
        </Button>
        <Badge
          v-if="activeFilterCount > 0"
          class="absolute -right-1 -top-1 h-5 min-w-5 items-center justify-center rounded-full px-1 text-xs"
          variant="secondary"
        >
          {{ activeFilterCount }}
        </Badge>
      </div>
    </div>

    <div class="flex flex-1 justify-center px-4">
      <div class="relative w-full max-w-lg">
        <Search
          class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
          aria-hidden
        />
        <Input
          :model-value="searchQuery ?? ''"
          type="search"
          class="h-9 rounded-lg pl-9 pr-8 focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:border-primary-500 [&::-webkit-search-cancel-button]:hidden"
          placeholder="Search in collection"
          aria-label="Search collection"
          @update:model-value="emit('update:searchQuery', $event ?? '')"
        />
        <button
          v-if="(searchQuery ?? '').length > 0"
          type="button"
          class="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
          aria-label="Clear search"
          @click="emit('update:searchQuery', '')"
        >
          <X class="h-4 w-4" />
        </button>
      </div>
    </div>

    <div class="flex flex-shrink-0 items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        class="gap-1.5 rounded-lg border-neutral-200 text-foreground hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-primary-500 focus-visible:outline-offset-2"
        aria-label="Collections"
      >
        <FolderOpen class="h-4 w-4" />
        <span class="hidden sm:inline">Collections</span>
      </Button>
      <Button
        variant="outline"
        size="icon"
        class="h-9 w-9 rounded-lg border-neutral-200 text-foreground hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-primary-500 focus-visible:outline-offset-2"
        aria-label="Info"
      >
        <Info class="h-4 w-4" />
      </Button>
      <Button
        variant="outline"
        size="icon"
        class="h-9 w-9 rounded-lg border-neutral-200 text-foreground hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-primary-500 focus-visible:outline-offset-2"
        aria-label="User"
      >
        <User class="h-4 w-4" />
      </Button>
      <Button
        variant="outline"
        size="sm"
        class="rounded-lg border-neutral-200 text-foreground hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-primary-500 focus-visible:outline-offset-2"
        aria-label="Language EN/SK"
      >
        EN/SK
      </Button>
    </div>
  </nav>

  <!-- Mobile nav: two rows -->
  <nav
    v-else
    class="fixed top-0 left-0 right-0 z-50 flex flex-col border-b border-neutral-200 bg-white"
    aria-label="Main navigation"
  >
    <!-- Row 1: branding + hamburger -->
    <div class="flex h-[49px] items-center justify-between px-4">
      <span class="truncate text-lg font-semibold text-primary-500">
        Etno Explorer SAV
      </span>
      <Sheet v-model:open="mobileSheetOpen">
        <SheetTrigger as-child>
          <Button
            variant="outline"
            size="icon"
            class="h-9 w-9 rounded-lg border-neutral-200 text-foreground hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-primary-500 focus-visible:outline-offset-2"
            aria-label="Open menu"
          >
            <Menu class="h-5 w-5" />
          </Button>
        </SheetTrigger>
        <SheetContent side="right" class="w-[280px] sm:max-w-[320px]">
          <SheetHeader>
            <SheetTitle>Menu</SheetTitle>
          </SheetHeader>
          <div class="mt-6 flex flex-col gap-2">
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <FolderOpen class="h-4 w-4" />
              Collections
            </Button>
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <Info class="h-4 w-4" />
              Info
            </Button>
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <User class="h-4 w-4" />
              User
            </Button>
            <Button
              variant="outline"
              class="justify-start gap-2"
              @click="mobileSheetOpen = false"
            >
              <Languages class="h-4 w-4" />
              EN/SK
            </Button>
          </div>
        </SheetContent>
      </Sheet>
    </div>
    <!-- Row 2: filter + search -->
    <div class="flex items-center gap-2 px-4 pb-2.5">
      <div class="relative shrink-0">
        <Button
          type="button"
          size="sm"
          class="gap-1.5 bg-primary-500 text-white hover:bg-primary-600"
          aria-label="Toggle filters"
          @click="emit('toggle-filter')"
        >
          <SlidersHorizontal class="h-4 w-4" />
          <span>Filter</span>
        </Button>
        <Badge
          v-if="activeFilterCount > 0"
          class="absolute -right-1 -top-1 h-5 min-w-5 items-center justify-center rounded-full px-1 text-xs"
          variant="secondary"
        >
          {{ activeFilterCount }}
        </Badge>
      </div>
      <div class="relative flex-1 min-w-0">
        <Search
          class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
          aria-hidden
        />
        <Input
          :model-value="searchQuery ?? ''"
          type="search"
          class="h-9 rounded-lg pl-9 pr-8 focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:border-primary-500 [&::-webkit-search-cancel-button]:hidden"
          placeholder="Search in collection"
          aria-label="Search collection"
          @update:model-value="emit('update:searchQuery', $event ?? '')"
        />
        <button
          v-if="(searchQuery ?? '').length > 0"
          type="button"
          class="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
          aria-label="Clear search"
          @click="emit('update:searchQuery', '')"
        >
          <X class="h-4 w-4" />
        </button>
      </div>
    </div>
  </nav>
</template>
